### ISSUE TITLE
[BUG]目前卡饭导出备份无法被转换

### ISSUE THREAD

**Issue by lkyu-ly** [nopdan/rose#6]
无论是用图形界面还是命令行，均无法将卡饭个人备份导出词库进行转换，下面是基本信息：
卡饭输入法版本：`1.0.0.300`
软件行为：先是一直重复类似的报错：`index out of range:  65539 > 439`，然后内存飙升（如下图）（待转换文件仅有1.9mb却直接吃满了电脑内存），然后程序报错退出。
![Clip_231221_1703](https://github.com/nopdan/rose/assets/67578466/162829c4-2e6a-47a6-8487-08885b4e7834)
如需其他信息可以再次复现。

**Comment by nopdan** [comment]
导出的是`拼音用户词库`还是`五笔用户词库`?

**Comment by lkyu-ly** [comment]
是拼音用户词库，如需文件可以提供



---原始邮件---
发件人: "Xing Chen · ***@***.***&gt;
发送时间: 2023年12月22日(周五) 中午1:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nopdan/rose] [BUG]目前卡饭导出备份无法被转换 (Issue #6)




 
导出的是拼音用户词库还是五笔用户词库?

**Comment by nopdan** [comment]
[rose.zip](https://github.com/nopdan/rose/files/13749188/rose.zip)
试试看

**Comment by lkyu-ly** [comment]
## 这次我对您 `release` 中的版本和上面的版本行为做了详细记录。
### 文件夹结构
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2023/12/22     19:18                data
-a----         2023/8/29     15:29           3559 CHANGELOG.md
-a----        2023/12/22     19:35              0 kfbf-rime_new.txt
-a----        2023/12/22     19:26             46 log_new.txt
-a----        2023/12/22     19:24        1356266 log_old.txt
-a----         2023/8/29     15:29           4509 README.md
-a----         2023/8/29     15:29        2912272 rose-darwin-amd64
-a----         2023/8/29     15:29        3162128 rose-darwin-arm64
-a----         2023/8/29     15:29        2736036 rose-linux
-a----         2023/8/29     15:29        2766336 rose-windows.exe
-a----        2023/12/22     14:51        5345280 rose.exe
-a----        2023/12/22     19:20              0 拼音词库备份2023-12-22.dict_Rime拼音.txt
```
### `release` 中的版本
1. 使用命令：`E:\Downloads\rose-v1.3.1\rose-windows.exe E:\Desktop\拼音词库备份2023-12-22.dict dict:rime kfbf-rime.txt > log_old.txt`
2. `log_old.txt`中的内容：[log_old.txt](https://github.com/nopdan/rose/files/13751901/log_old.txt)
3. 命令行输出内容（报错）：貌似是炸内存
    ```
    runtime: VirtualAlloc of 9193357312 bytes failed with errno=1455
    fatal error: out of memory
    
    runtime stack:
    runtime.throw({0xadd2ef?, 0xc6c0907000?})
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/panic.go:1077 +0x65 fp=0xd36f9ffa88 sp=0xd36f9ffa58 pc=0x7e7525
    runtime.sysUsedOS(0xc59c224000, 0x223f78000)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mem_windows.go:83 +0x1bb fp=0xd36f9ffae8 sp=0xd36f9ffa88 pc=0x7c6f7b
    runtime.sysUsed(...)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mem.go:77
    runtime.(*mheap).allocSpan(0xe82540, 0x111fbc, 0x0, 0xda?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mheap.go:1351 +0x487 fp=0xd36f9ffb88 sp=0xd36f9ffae8 pc=0x7d8447
    runtime.(*mheap).alloc.func1()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mheap.go:968 +0x5c fp=0xd36f9ffbd0 sp=0xd36f9ffb88 pc=0x7d7bfc
    runtime.systemstack()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:509 +0x49 fp=0xd36f9ffbe0 sp=0xd36f9ffbd0 pc=0x8150a9
    
    goroutine 1 [running]:
    runtime.systemstack_switch()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:474 +0x8 fp=0xc002a099e0 sp=0xc002a099d0 pc=0x815048
    runtime.(*mheap).alloc(0x223f78000?, 0x111fbc?, 0xa5?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mheap.go:962 +0x5b fp=0xc002a09a28 sp=0xc002a099e0 pc=0x7d7b5b
    runtime.(*mcache).allocLarge(0x1d6fe3e2090?, 0x223f78000, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mcache.go:234 +0x85 fp=0xc002a09a70 sp=0xc002a09a28 pc=0x7c5e45
    runtime.mallocgc(0x223f78000, 0xa75420, 0x1)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/malloc.go:1123 +0x4f6 fp=0xc002a09ad8 sp=0xc002a09a70 pc=0x7bd276
    runtime.growslice(0xc3e5c2c000, 0xc10896fce0?, 0x28?, 0x28?, 0xa75420)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/slice.go:274 +0x510 fp=0xc002a09b48 sp=0xc002a09ad8 pc=0x7fc010
    github.com/nopdan/rose/pkg/pinyin.(*Kafan).Unmarshal(0xc00000a110?, 0xc000023560)
            /home/runner/work/rose/rose/pkg/pinyin/kafan.go:489 +0x57e fp=0xc002a09c50 sp=0xc002a09b48 pc=0xa2411e
    github.com/nopdan/rose/pkg/core.(*Config).Marshal(0xc002a09dd8)
            /home/runner/work/rose/rose/pkg/core/core.go:86 +0x1e3 fp=0xc002a09d88 sp=0xc002a09c50 pc=0xa51e63
    github.com/nopdan/rose/cmd.root()
            /home/runner/work/rose/rose/cmd/cmd.go:85 +0x125 fp=0xc002a09e88 sp=0xc002a09d88 pc=0xa54f65
    github.com/nopdan/rose/cmd.Cmd()
            /home/runner/work/rose/rose/cmd/cmd.go:51 +0x34d fp=0xc002a09f30 sp=0xc002a09e88 pc=0xa54bcd
    main.main()
            /home/runner/work/rose/rose/main.go:9 +0xf fp=0xc002a09f40 sp=0xc002a09f30 pc=0xa5504f
    runtime.main()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:267 +0x2b2 fp=0xc002a09fe0 sp=0xc002a09f40 pc=0x7e9d72
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc002a09fe8 sp=0xc002a09fe0 pc=0x817061
    
    goroutine 2 [force gc (idle), 1 minutes]:
    runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000057fa8 sp=0xc000057f88 pc=0x7ea18e
    runtime.goparkunlock(...)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:404
    runtime.forcegchelper()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:322 +0xb8 fp=0xc000057fe0 sp=0xc000057fa8 pc=0x7ea018
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x817061
    created by runtime.init.6 in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:310 +0x1a
    
    goroutine 3 [GC sweep wait]:
    runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000059f78 sp=0xc000059f58 pc=0x7ea18e
    runtime.goparkunlock(...)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:404
    runtime.bgsweep(0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgcsweep.go:321 +0xdf fp=0xc000059fc8 sp=0xc000059f78 pc=0x7d495f
    runtime.gcenable.func1()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:200 +0x25 fp=0xc000059fe0 sp=0xc000059fc8 pc=0x7c9c65
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0x817061
    created by runtime.gcenable in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:200 +0x66
    
    goroutine 4 [sleep]:
    runtime.gopark(0xc000072000?, 0x88318ea5da?, 0x0?, 0x0?, 0xb84730?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc00006bf30 sp=0xc00006bf10 pc=0x7ea18e
    runtime.goparkunlock(...)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:404
    runtime.(*scavengerState).sleep(0xe6c1c0, 0x4131170000000000)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgcscavenge.go:504 +0x118 fp=0xc00006bfa0 sp=0xc00006bf30 pc=0x7d2378
    runtime.bgscavenge(0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgcscavenge.go:662 +0x74 fp=0xc00006bfc8 sp=0xc00006bfa0 pc=0x7d2774
    runtime.gcenable.func2()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:201 +0x25 fp=0xc00006bfe0 sp=0xc00006bfc8 pc=0x7c9c05
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x817061
    created by runtime.gcenable in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:201 +0xa5
    
    goroutine 5 [finalizer wait, 1 minutes]:
    runtime.gopark(0x0?, 0xb84660?, 0x40?, 0x15?, 0x2000000020?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc00005be28 sp=0xc00005be08 pc=0x7ea18e
    runtime.runfinq()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mfinal.go:193 +0x107 fp=0xc00005bfe0 sp=0xc00005be28 pc=0x7c8d27
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x817061
    created by runtime.createfing in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mfinal.go:163 +0x3d
    
    goroutine 84 [GC worker (idle)]:
    runtime.gopark(0xec1220?, 0x1?, 0xa0?, 0x9?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000397f50 sp=0xc000397f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc000397fe0 sp=0xc000397f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000397fe8 sp=0xc000397fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 87 [GC worker (idle)]:
    runtime.gopark(0xec1220?, 0x1?, 0x0?, 0xbc?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000393f50 sp=0xc000393f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc000393fe0 sp=0xc000393f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000393fe8 sp=0xc000393fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 83 [GC worker (idle)]:
    runtime.gopark(0x857fcd8fd4?, 0x3?, 0x10?, 0x52?, 0x2?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc00039ff50 sp=0xc00039ff30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc00039ffe0 sp=0xc00039ff50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00039ffe8 sp=0xc00039ffe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 50 [GC worker (idle), 1 minutes]:
    runtime.gopark(0xadd0cc?, 0xc?, 0xe1?, 0x95?, 0x2?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc0003a5f50 sp=0xc0003a5f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc0003a5fe0 sp=0xc0003a5f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003a5fe8 sp=0xc0003a5fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 88 [GC worker (idle)]:
    runtime.gopark(0x857fcd8fd4?, 0x3?, 0x88?, 0x3?, 0x2?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc0003b1f50 sp=0xc0003b1f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc0003b1fe0 sp=0xc0003b1f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003b1fe8 sp=0xc0003b1fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 86 [GC worker (idle)]:
    runtime.gopark(0xec1220?, 0x1?, 0xe4?, 0xc0?, 0x2?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc0003abf50 sp=0xc0003abf30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc0003abfe0 sp=0xc0003abf50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003abfe8 sp=0xc0003abfe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 82 [GC worker (idle)]:
    runtime.gopark(0xec1220?, 0x1?, 0x40?, 0xab?, 0x2?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc0003b9f50 sp=0xc0003b9f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc0003b9fe0 sp=0xc0003b9f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003b9fe8 sp=0xc0003b9fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 85 [GC worker (idle)]:
    runtime.gopark(0x857f076ebc?, 0x3?, 0xf4?, 0xef?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc0003c5f50 sp=0xc0003c5f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc0003c5fe0 sp=0xc0003c5f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003c5fe8 sp=0xc0003c5fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 66 [GC worker (idle)]:
    runtime.gopark(0x857fcd8fd4?, 0x3?, 0x38?, 0x2a?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc0003ddf50 sp=0xc0003ddf30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc0003ddfe0 sp=0xc0003ddf50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003ddfe8 sp=0xc0003ddfe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 67 [GC worker (idle)]:
    runtime.gopark(0x857f076ebc?, 0x3?, 0x0?, 0xef?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc0003dff50 sp=0xc0003dff30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc0003dffe0 sp=0xc0003dff50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003dffe8 sp=0xc0003dffe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 68 [GC worker (idle)]:
    runtime.gopark(0x857ef8105c?, 0x3?, 0x2c?, 0xa2?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000509f50 sp=0xc000509f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc000509fe0 sp=0xc000509f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000509fe8 sp=0xc000509fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 69 [GC worker (idle)]:
    runtime.gopark(0xec1220?, 0x1?, 0x98?, 0x16?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc00050bf50 sp=0xc00050bf30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc00050bfe0 sp=0xc00050bf50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00050bfe8 sp=0xc00050bfe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 70 [GC worker (idle)]:
    runtime.gopark(0x857ef8105c?, 0x3?, 0x14?, 0xd9?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000505f50 sp=0xc000505f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc000505fe0 sp=0xc000505f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000505fe8 sp=0xc000505fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 71 [GC worker (idle)]:
    runtime.gopark(0x857fe16dc4?, 0x1?, 0x18?, 0x2b?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000507f50 sp=0xc000507f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc000507fe0 sp=0xc000507f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000507fe8 sp=0xc000507fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 72 [GC worker (idle)]:
    runtime.gopark(0x857f076ebc?, 0x3?, 0x40?, 0x54?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000511f50 sp=0xc000511f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc000511fe0 sp=0xc000511f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000511fe8 sp=0xc000511fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    
    goroutine 73 [GC worker (idle)]:
    runtime.gopark(0x857f076ebc?, 0x3?, 0xfc?, 0x18?, 0x0?)
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000513f50 sp=0xc000513f30 pc=0x7ea18e
    runtime.gcBgMarkWorker()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc000513fe0 sp=0xc000513f50 pc=0x7cb665
    runtime.goexit()
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000513fe8 sp=0xc000513fe0 pc=0x817061
    created by runtime.gcBgMarkStartWorkers in goroutine 1
            /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c
    ```

### 新版本
1. 使用命令：`E:\Downloads\rose-v1.3.1\rose.exe E:\Desktop\拼音词库备份2023-12-22.dict dict:rime kfbf-rime_new.txt`
2. 程序立刻完成
3. 命令行输出报错：`卡饭拼音备份.dict格式错误`
4. 输出转换后文件为空文件
